# Generated by Django 5.0.7 on 2024-08-16 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web', '0004_menu_intdjangocontenttype_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_web_menu_permission',
            fields=[
                ('intAuthUserWebPermision_id', models.AutoField(primary_key=True, serialize=False)),
                ('intGroup_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.group')),
                ('intWebMenu_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.menu')),
            ],
            options={
                'permissions': [],
            },
        ),
    ]
