# Generated by Django 5.0.7 on 2024-08-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_intauthuserwebpermision_id_group_web_menu_permission_intauthgroupwebpermision_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_web_menu_permission',
            old_name='intGroup_id',
            new_name='intGroup',
        ),
        migrations.RenameField(
            model_name='group_web_menu_permission',
            old_name='intWebMenu_id',
            new_name='intWebMenu',
        ),
        migrations.RenameField(
            model_name='user_web_menu_permission',
            old_name='intUser_id',
            new_name='intUser',
        ),
        migrations.RenameField(
            model_name='user_web_menu_permission',
            old_name='intWebMenu_id',
            new_name='intWebMenu',
        ),
    ]
