# Generated by Django 5.0.7 on 2024-08-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_intdjangocontenttype_menu_intdjangocontenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='intWebMenu_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='strWebMenu_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
