# Generated by Django 5.0.7 on 2024-08-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_menu_intwebmenu_rank_menu_strwebmenu_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='strWebMenu_route',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
