# Generated by Django 5.0.7 on 2024-08-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_menu_strwebmenu_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='strWebMenu_childernId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='strWebMenu_route',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='strWebMenu_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
