# Generated by Django 5.0.7 on 2024-08-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_menu_strwebmenu_childernid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='strWebMenu_childernId',
            new_name='intWebMenu_childernId',
        ),
    ]
