# Generated by Django 5.1.2 on 2024-10-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_menu_intdjangocontenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='strWebMenu_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
