# Generated by Django 5.1.2 on 2024-10-23 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
