# Generated by Django 5.1.2 on 2024-10-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='strMenu_name',
        ),
    ]
