# Generated by Django 5.1.2 on 2024-10-23 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_remove_menu_strmenu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_menu_permission',
            name='intMenu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='FK_menus_user_menu_permission', to='web.menu'),
        ),
    ]
