# Generated by Django 5.1.2 on 2024-10-25 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_rename_intgroup_id_group_menu_permission_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_menu_permission',
            name='Menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='FK_UserMenuPermission_Menu', to='web.menu'),
        ),
        migrations.AlterField(
            model_name='user_menu_permission',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='FK_UserMenuPermission_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
