# Generated by Django 5.1.2 on 2024-10-25 08:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web', '0023_alter_user_menu_permission_menu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group_menu_permission',
            options={'ordering': ['Menu'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='user_menu_permission',
            options={'ordering': ['Menu'], 'permissions': []},
        ),
        migrations.AlterUniqueTogether(
            name='group_menu_permission',
            unique_together={('Menu', 'Group')},
        ),
        migrations.AlterUniqueTogether(
            name='user_menu_permission',
            unique_together={('Menu', 'User')},
        ),
    ]
